// src/pages/app/App.tsx
import React, { useLayoutEffect } from "react";
import { useHistory } from "react-router";
import { makeStyles, Theme, darken } from "@material-ui/core";
import { Connection } from "@harmony-dev/harmony-web-sdk";

import { HarmonyStorage } from "../../storage/HarmonyStorage";
import { Comms } from "../../comms/Comms";

import { GuildList } from "./guildlist/GuildList";
import { GuildDialog } from "./guilddialog/GuildDialog";
import { ChannelList } from "./channellist/ChannelList";

const appStyles = makeStyles((theme: Theme) => ({
  root: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "row",
    overflow: "auto",
  },
  guildlist: {
    padding: "8px",
    backgroundColor: darken(theme.palette.background.default, 0.5),
    borderRight: "1px solid grey",
    display: "flex",
    flexDirection: "column",
  },
  channellist: {
    width: "400px",
    overflowY: "auto",
    backgroundColor: darken(theme.palette.background.default, 0.25),
  },
  memberlist: {
    width: "350px",
    overflowY: "auto",
    backgroundColor: darken(theme.palette.background.default, 0.25),
  },
  chat: {
    display: "flex",
    flexDirection: "column",
    flexFlow: "column",
    width: "100%",
    height: "100%",
  },
}));

const _App = () => {
  const classes = appStyles();
  const history = useHistory();

  useLayoutEffect(() => {
    const homeserver = HarmonyStorage.getHomeserver();
    const session = HarmonyStorage.getSession();
    const userid = HarmonyStorage.getUserID();
    if (!homeserver || !session || !userid) {
      history.push("/entry/serverselect");
      return;
    }
    if (!Comms.homeserver) {
      Comms.homeserver = homeserver;
      Comms.connections[homeserver] = new Connection(homeserver);
      Comms.connections[homeserver].session = session;
    }
    // eslint-disable-next-line
  }, []);

  return (
    <>
      <div className={classes.root}>
        <div className={classes.guildlist}>
          <GuildList />
        </div>
        <div className={classes.channellist}>
          <ChannelList />
        </div>
        <div className={classes.chat}></div>
        <div className={classes.memberlist}></div>
      </div>
      <GuildDialog />
    </>
  );
};

export const App = React.memo(_App);

// pages/_app.vue
<template>
  <div class="root">
    <guild-list />
    <channel-list />
    <chat />
    <member-list />
  </div>
</template>

<style scoped>
.root {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: row;
  overflow: auto;
}
</style>

<script lang="ts">
import Vue from 'vue'
import GuildList from '@/components/GuildList/index.vue'
import ChannelList from '@/components/ChannelList/index.vue'
import MemberList from '@/components/MemberList.vue'
import Chat from '@/components/Chat.vue'
import { Connection } from '@harmony-dev/harmony-web-sdk'

export default Vue.extend({
  components: {
    GuildList,
    ChannelList,
    MemberList,
    Chat,
  },
  created() {
    if (!this.$accessor.app.host || !this.$accessor.app.session) {
      this.$router.push('entry')
      return
    }
    const conn = new Connection(this.$accessor.app.host)
    this.$accessor.app.setConnection({
      host: this.$accessor.app.host,
      connection: conn,
    })
    conn.session = this.$accessor.app.session
  },
})
</script>
